import { AnimationPreset } from '../types/animation';

export const ANIMATION_PRESETS: AnimationPreset[] = [
  {
    id: 'slow-scroll',
    name: 'Slow Scroll',
    tag: 'ELEGANT / AMBIENT',
    description: 'Smooth, serene linear glide with gentle harmonic breathing and zero harsh distortion.',
    iconName: 'Wind',
    settings: {
      marqueeSpeed: 18,
      scaleRhythm: 4.2,
      scaleIntensity: 1.06,
      skewAngle: 0,
      skewAnimation: false,
      waveDistortion: false,
      chromaticAberration: false,
      timingFunction: 'linear',
      bpmSync: false,
    },
  },
  {
    id: 'fast-warp',
    name: 'Fast Warp',
    tag: 'HIGH VELOCITY',
    description: 'High-speed kinetic rush with aggressive dynamic skew angles and wave distortion.',
    iconName: 'Zap',
    settings: {
      marqueeSpeed: 4.5,
      scaleRhythm: 1.6,
      scaleIntensity: 1.32,
      skewAngle: -14,
      skewAnimation: true,
      waveDistortion: true,
      chromaticAberration: true,
      timingFunction: 'cubic-punch',
      bpmSync: true,
      bpm: 150,
    },
  },
  {
    id: 'rhythmic-pulse',
    name: 'Rhythmic Pulse',
    tag: 'PERCUSSIVE / BEAT',
    description: 'Punchy BPM-synchronized bounce with rhythmic typography expansion and heavy impact scale.',
    iconName: 'Activity',
    settings: {
      marqueeSpeed: 8,
      scaleRhythm: 1.8,
      scaleIntensity: 1.28,
      skewAngle: 6,
      skewAnimation: true,
      waveDistortion: false,
      chromaticAberration: false,
      timingFunction: 'cubic-punch',
      bpmSync: true,
      bpm: 130,
    },
  },
  {
    id: 'strobe-glitch',
    name: 'Strobe Glitch',
    tag: 'CYBER / RGB SPLIT',
    description: 'High-frequency stepped micro-stutter with active RGB chromatic split and rapid cycling.',
    iconName: 'Sparkles',
    settings: {
      marqueeSpeed: 5,
      scaleRhythm: 0.9,
      scaleIntensity: 1.22,
      skewAngle: -8,
      skewAnimation: true,
      waveDistortion: true,
      chromaticAberration: true,
      timingFunction: 'steps-glitch',
      bpmSync: false,
    },
  },
  {
    id: 'hypnotic-float',
    name: 'Hypnotic Float',
    tag: 'ORGANIC / SINE',
    description: 'Undulating sinusoidal oscillation with gentle skew sweeps and fluid optical warp.',
    iconName: 'Radio',
    settings: {
      marqueeSpeed: 12,
      scaleRhythm: 3.0,
      scaleIntensity: 1.18,
      skewAngle: 10,
      skewAnimation: true,
      waveDistortion: true,
      chromaticAberration: false,
      timingFunction: 'ease-in-out',
      bpmSync: false,
    },
  },
];
