import { PosterPreset } from '../types';

export const POSTER_PRESETS: PosterPreset[] = [
  {
    id: 'kinetic-reality',
    name: 'KINETIC REALITY',
    category: 'Kinetic Brutalism',
    description: 'Alternating high-speed marquees with rhythmic pulse distortion.',
    config: {
      mainHeadline: 'KINETIC // REALITY',
      subHeadline: 'DYNAMIC BRUTALIST EXPERIMENT',
      tickerText: 'FREQUENCY MODULATION ★ 140 BPM ★ RAW CSS ENGINE ★ ZERO JAVASCRIPT ANIMATION OVERHEAD ★',
      locationStamp: 'BERLIN / KREUZBERG',
      dateStamp: '2026.08.25',
      editionCode: 'SYS-KP-001',
      layout: 'multi-ribbon',
      aspectRatio: '4:5',
      marqueeSpeed: 10,
      scaleRhythm: 2.4,
      scaleIntensity: 1.15,
      skewAngle: 0,
      skewAnimation: false,
      waveDistortion: true,
      fontFamily: 'Unbounded',
      fontWeight: 900,
      letterSpacing: -0.04,
      uppercase: true,
      outlineMode: false,
      strokeWidth: 2,
      paletteId: 'neon',
      showScanlines: true,
      showGrain: true,
      showGridLines: true,
      showCrosshairs: true,
      showBarcode: true,
      chromaticAberration: true,
      invertOnHover: true,
      bpmSync: false,
      bpm: 128,
    },
  },
  {
    id: 'swiss-construct',
    name: 'SWISS MONOCHROME',
    category: 'Swiss International',
    description: 'Clean, high-contrast monochrome poster with stark grid guides and micro-typography.',
    config: {
      mainHeadline: 'TYPOGRAPHIE',
      subHeadline: 'RHYTHMUS & BEWEGUNG',
      tickerText: 'INTERNATIONAL TYPOGRAPHIC STYLE — ZÜRICH 1957 — REVISED 2026 — FORM FOLLOWS FREQUENCY —',
      locationStamp: 'ZÜRICH / SCHWEIZ',
      dateStamp: '1957 // 2026',
      editionCode: 'SWISS-ORD-88',
      layout: 'brutalist-block',
      aspectRatio: '3:4',
      marqueeSpeed: 14,
      scaleRhythm: 3.2,
      scaleIntensity: 1.08,
      skewAngle: 0,
      skewAnimation: false,
      waveDistortion: false,
      fontFamily: 'Syne',
      fontWeight: 800,
      letterSpacing: 0.02,
      uppercase: true,
      outlineMode: false,
      strokeWidth: 1,
      paletteId: 'monochrome',
      showScanlines: false,
      showGrain: true,
      showGridLines: true,
      showCrosshairs: true,
      showBarcode: true,
      chromaticAberration: false,
      invertOnHover: true,
      bpmSync: false,
      bpm: 120,
    },
  },
  {
    id: 'cyber-hyperdrive',
    name: 'NEO CYBERPUNK 2099',
    category: 'Cyberpunk',
    description: 'Slanted diagonal 45deg kinetic ribbon storm with CRT scanlines and chromatic glitch.',
    config: {
      mainHeadline: 'CYBER//SYSTEM',
      subHeadline: 'NEURAL TYPOGRAPHY MATRIX',
      tickerText: 'SYSTEM OVERLOAD >> OPTICAL LINK ESTABLISHED >> SYNCHRONIZING BUFFER >> NEON DISTRICT 04 >>',
      locationStamp: 'SHINJUKU / SECTOR 9',
      dateStamp: '2099.11.04',
      editionCode: 'CYBER-CORE-X',
      layout: 'diagonal-slash',
      aspectRatio: '9:16',
      marqueeSpeed: 7,
      scaleRhythm: 1.8,
      scaleIntensity: 1.22,
      skewAngle: -14,
      skewAnimation: true,
      waveDistortion: true,
      fontFamily: 'Anton',
      fontWeight: 900,
      letterSpacing: 0.05,
      uppercase: true,
      outlineMode: false,
      strokeWidth: 2,
      paletteId: 'cyberpunk',
      showScanlines: true,
      showGrain: true,
      showGridLines: true,
      showCrosshairs: true,
      showBarcode: true,
      chromaticAberration: true,
      invertOnHover: true,
      bpmSync: true,
      bpm: 145,
    },
  },
  {
    id: 'acid-rave',
    name: 'ACID FREQUENCY',
    category: 'Club / Rave Poster',
    description: 'High energy 3D cylinder kinetic warp with toxic strobe contrast.',
    config: {
      mainHeadline: 'SUB_AUDIO',
      subHeadline: 'ALL NIGHT INDUSTRIAL RAVE',
      tickerText: 'HEAVY BASSLINE ⚡ 303 SYNTHESIZER ⚡ ANALOG DISTORTION ⚡ 22:00 TIL LATE ⚡ DRINK WATER ⚡',
      locationStamp: 'KRAFTWERK / VAULT',
      dateStamp: 'SATURDAY 03:00',
      editionCode: 'RAVE-303-ACID',
      layout: 'cylinder-3d',
      aspectRatio: '4:5',
      marqueeSpeed: 6,
      scaleRhythm: 1.5,
      scaleIntensity: 1.25,
      skewAngle: 8,
      skewAnimation: true,
      waveDistortion: true,
      fontFamily: 'Rubik Glitch',
      fontWeight: 700,
      letterSpacing: 0.08,
      uppercase: true,
      outlineMode: false,
      strokeWidth: 2,
      paletteId: 'thermal',
      showScanlines: true,
      showGrain: true,
      showGridLines: true,
      showCrosshairs: true,
      showBarcode: true,
      chromaticAberration: true,
      invertOnHover: true,
      bpmSync: true,
      bpm: 138,
    },
  },
  {
    id: 'bauhaus-manifesto',
    name: 'BAUHAUS MANIFESTO',
    category: 'Constructivism',
    description: 'Warm editorial canvas with striking red/ink contrast and dual-tone kinetic blocks.',
    config: {
      mainHeadline: 'KRAFT & FORM',
      subHeadline: 'EXPERIMENTELLE TYPOGRAPHIE',
      tickerText: 'DIE NEUE TYPOGRAPHIE ★ FUNKTION UND ÄSTHETIK ★ DER REINE AUSDRUCK ★ DESSAU 1925 ★',
      locationStamp: 'WEIMAR // DESSAU',
      dateStamp: '1925 // 2026',
      editionCode: 'BH-EDITION-04',
      layout: 'monolith-split',
      aspectRatio: '1:1',
      marqueeSpeed: 12,
      scaleRhythm: 2.8,
      scaleIntensity: 1.1,
      skewAngle: 0,
      skewAnimation: false,
      waveDistortion: false,
      fontFamily: 'Bebas Neue',
      fontWeight: 800,
      letterSpacing: 0.12,
      uppercase: true,
      outlineMode: false,
      strokeWidth: 2,
      paletteId: 'acid',
      showScanlines: false,
      showGrain: true,
      showGridLines: true,
      showCrosshairs: true,
      showBarcode: true,
      chromaticAberration: false,
      invertOnHover: true,
      bpmSync: false,
      bpm: 110,
    },
  },
  {
    id: 'hyper-matrix',
    name: 'RAW CODE MATRIX',
    category: 'Generative Tech',
    description: 'Dense terminal mono tickers with outline typography and digital scanlines.',
    config: {
      mainHeadline: 'ASCII_BUFFER',
      subHeadline: 'TERMINAL PROTOCOL V4',
      tickerText: '01001011 01001001 01001110 01000101 01010100 01001001 01000011 // RAW CSS PIPELINE //',
      locationStamp: 'ROOT // CONSOLE',
      dateStamp: '0x7FFD9A',
      editionCode: 'HEX-TTY-09',
      layout: 'matrix-ticker',
      aspectRatio: '16:9',
      marqueeSpeed: 8,
      scaleRhythm: 2.0,
      scaleIntensity: 1.12,
      skewAngle: -4,
      skewAnimation: false,
      waveDistortion: true,
      fontFamily: 'JetBrains Mono',
      fontWeight: 800,
      letterSpacing: -0.02,
      uppercase: true,
      outlineMode: true,
      strokeWidth: 2,
      paletteId: 'hyperpop',
      showScanlines: true,
      showGrain: true,
      showGridLines: true,
      showCrosshairs: true,
      showBarcode: true,
      chromaticAberration: true,
      invertOnHover: true,
      bpmSync: false,
      bpm: 128,
    },
  },
];
